-- Add statistics columns to derived_assets

ALTER TABLE derived_assets
ADD COLUMN IF NOT EXISTS ndvi_mean FLOAT,
ADD COLUMN IF NOT EXISTS ndvi_min FLOAT,
ADD COLUMN IF NOT EXISTS ndvi_max FLOAT,
ADD COLUMN IF NOT EXISTS ndvi_std FLOAT,

ADD COLUMN IF NOT EXISTS ndwi_mean FLOAT,
ADD COLUMN IF NOT EXISTS ndwi_min FLOAT,
ADD COLUMN IF NOT EXISTS ndwi_max FLOAT,
ADD COLUMN IF NOT EXISTS ndwi_std FLOAT,

ADD COLUMN IF NOT EXISTS ndmi_mean FLOAT,
ADD COLUMN IF NOT EXISTS ndmi_min FLOAT,
ADD COLUMN IF NOT EXISTS ndmi_max FLOAT,
ADD COLUMN IF NOT EXISTS ndmi_std FLOAT,

ADD COLUMN IF NOT EXISTS savi_mean FLOAT,
ADD COLUMN IF NOT EXISTS savi_min FLOAT,
ADD COLUMN IF NOT EXISTS savi_max FLOAT,
ADD COLUMN IF NOT EXISTS savi_std FLOAT,

ADD COLUMN IF NOT EXISTS anomaly_mean FLOAT,
ADD COLUMN IF NOT EXISTS anomaly_std FLOAT;
