-- Add columns for Advanced Indices (Optical + Radar)

ALTER TABLE derived_assets
-- S3 URIs (Optical)
ADD COLUMN IF NOT EXISTS ndre_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS reci_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS gndvi_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS evi_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS msi_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS nbr_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS bsi_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS ari_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS cri_s3_uri TEXT,

-- S3 URIs (Radar)
ADD COLUMN IF NOT EXISTS rvi_s3_uri TEXT,
ADD COLUMN IF NOT EXISTS ratio_s3_uri TEXT,

-- Statistics (Optical)
-- NDRE
ADD COLUMN IF NOT EXISTS ndre_mean FLOAT,
ADD COLUMN IF NOT EXISTS ndre_min FLOAT,
ADD COLUMN IF NOT EXISTS ndre_max FLOAT,
ADD COLUMN IF NOT EXISTS ndre_std FLOAT,

-- RECI
ADD COLUMN IF NOT EXISTS reci_mean FLOAT,
ADD COLUMN IF NOT EXISTS reci_min FLOAT,
ADD COLUMN IF NOT EXISTS reci_max FLOAT,
ADD COLUMN IF NOT EXISTS reci_std FLOAT,

-- GNDVI
ADD COLUMN IF NOT EXISTS gndvi_mean FLOAT,
ADD COLUMN IF NOT EXISTS gndvi_min FLOAT,
ADD COLUMN IF NOT EXISTS gndvi_max FLOAT,
ADD COLUMN IF NOT EXISTS gndvi_std FLOAT,

-- EVI
ADD COLUMN IF NOT EXISTS evi_mean FLOAT,
ADD COLUMN IF NOT EXISTS evi_min FLOAT,
ADD COLUMN IF NOT EXISTS evi_max FLOAT,
ADD COLUMN IF NOT EXISTS evi_std FLOAT,

-- MSI
ADD COLUMN IF NOT EXISTS msi_mean FLOAT,
ADD COLUMN IF NOT EXISTS msi_min FLOAT,
ADD COLUMN IF NOT EXISTS msi_max FLOAT,
ADD COLUMN IF NOT EXISTS msi_std FLOAT,

-- NBR
ADD COLUMN IF NOT EXISTS nbr_mean FLOAT,
ADD COLUMN IF NOT EXISTS nbr_min FLOAT,
ADD COLUMN IF NOT EXISTS nbr_max FLOAT,
ADD COLUMN IF NOT EXISTS nbr_std FLOAT,

-- BSI
ADD COLUMN IF NOT EXISTS bsi_mean FLOAT,
ADD COLUMN IF NOT EXISTS bsi_min FLOAT,
ADD COLUMN IF NOT EXISTS bsi_max FLOAT,
ADD COLUMN IF NOT EXISTS bsi_std FLOAT,

-- ARI
ADD COLUMN IF NOT EXISTS ari_mean FLOAT,
ADD COLUMN IF NOT EXISTS ari_min FLOAT,
ADD COLUMN IF NOT EXISTS ari_max FLOAT,
ADD COLUMN IF NOT EXISTS ari_std FLOAT,

-- CRI
ADD COLUMN IF NOT EXISTS cri_mean FLOAT,
ADD COLUMN IF NOT EXISTS cri_min FLOAT,
ADD COLUMN IF NOT EXISTS cri_max FLOAT,
ADD COLUMN IF NOT EXISTS cri_std FLOAT;
